// examples/svelte-kit-example/src/lib/components/ui/breadcrumb/breadcrumb-list.svelte
<script lang="ts">
import { cn } from "$lib/utils";
import type { HTMLOlAttributes } from "svelte/elements";

type $$Props = HTMLOlAttributes & {
	el?: HTMLOListElement;
};

export let el: $$Props["el"] = undefined;
let className: $$Props["class"] = undefined;
export { className as class };
</script>

<ol
	bind:this={el}
	class={cn(
		"text-muted-foreground flex flex-wrap items-center gap-1.5 break-words text-sm sm:gap-2.5",
		className
	)}
	{...$$restProps}
>
	<slot />
</ol>

// examples/nuxt-example/components/ui/breadcrumb/BreadcrumbList.vue
<script lang="ts" setup>
import type { HTMLAttributes } from "vue";
import { cn } from "@/lib/utils";

const props = defineProps<{
	class?: HTMLAttributes["class"];
}>();
</script>

<template>
  <ol
    :class="cn('flex flex-wrap items-center gap-1.5 break-words text-sm text-muted-foreground sm:gap-2.5', props.class)"
  >
    <slot />
  </ol>
</template>
