// examples/nuxt-example/pages/reset-password.vue
<script lang="ts" setup>
import { resetPassword } from "~/lib/auth-client.js";

const confirmPassword = ref("");
const password = ref("");

const handleResetPassword = async () => {
	if (confirmPassword.value !== password.value) {
		alert("Please enter same passwords");
		return;
	}

	await resetPassword({
		newPassword: password.value,
		fetchOptions: {
			onSuccess(context) {
				window.location.href = "/sign-in";
			},
			onError(context) {
				alert(context.error.message);
			},
		},
	});
};
</script>

<template>
	<div class="h-screen flex justify-center items-center">
		<CardRoot class="mx-auto max-w-sm">
			<CardHeader>
				<CardTitle class="text-2xl">Reset Password</CardTitle>
				<CardDescription>Enter your new password below</CardDescription>
			</CardHeader>
			<CardContent>
				<div class="grid gap-4">
					<div class="grid gap-2">
						<Label for="password">New Password</Label>
						<Input id="password" type="password" required v-model="password" placeholder="New Password" />
					</div>
					<div class="grid gap-2">
						<Label for="password">Confirm Password</Label>
						<Input id="password" type="password" required placeholder="Confirm Password"
							v-model="confirmPassword" />
					</div>
					<Button type="button" class="w-full" @click="handleResetPassword">Reset</Button>
				</div>
			</CardContent>
		</CardRoot>
	</div>
</template>

// examples/svelte-kit-example/src/routes/reset-password/+page.svelte
<script>
	import * as Card from '$lib/components/ui/card/index';
	import Label from '$lib/components/ui/label/label.svelte';
	import Input from '$lib/components/ui/input/input.svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import { client } from '$lib/auth-client';

	let confirmPassword = '';
	let password = '';
</script>

<Card.Root class="mx-auto ">
	<Card.Header>
		<Card.Title class="text-2xl">Reset Password</Card.Title>
		<Card.Description>Enter your new password below</Card.Description>
	</Card.Header>
	<Card.Content>
		<div class="grid gap-4">
			<div class="grid gap-2">
				<Label for="password">New Password</Label>
				<Input id="password" type="password" required bind:value={password} placeholder="New Password" />
			</div>
			<div class="grid gap-2">
				<Label for="password">Confirm Password</Label>
				<Input id="password" type="password" required placeholder="Confirm Password" bind:value={confirmPassword} />
			</div>
			<Button
				type="button"
				class="w-full"
				on:click={async () => {
					await client.resetPassword({
						newPassword: password,
						fetchOptions: {
							onSuccess(context) {
								window.location.href = '/sign-in';
							},
							onError(context) {
								alert(context.error.message);
							},
						},
					});
				}}>Reset</Button
			>
		</div>
	</Card.Content>
</Card.Root>
