// examples/svelte-kit-example/src/lib/components/ui/calendar/calendar-cell.svelte
<script lang="ts">
import { Calendar as CalendarPrimitive } from "bits-ui";
import { cn } from "$lib/utils.js";

type $$Props = CalendarPrimitive.CellProps;

export let date: $$Props["date"];
let className: $$Props["class"] = undefined;
export { className as class };
</script>

<CalendarPrimitive.Cell
	{date}
	class={cn(
		"[&:has([data-selected])]:bg-accent [&:has([data-selected][data-outside-month])]:bg-accent/50 relative p-0 text-center text-sm focus-within:relative focus-within:z-20 [&:has([data-selected])]:rounded-md",
		className
	)}
	{...$$restProps}
>
	<slot />
</CalendarPrimitive.Cell>

// examples/nuxt-example/components/ui/calendar/CalendarCell.vue
<script lang="ts" setup>
import { type HTMLAttributes, computed } from "vue";
import {
	CalendarCell,
	type CalendarCellProps,
	useForwardProps,
} from "radix-vue";
import { cn } from "@/lib/utils";

const props = defineProps<
	CalendarCellProps & { class?: HTMLAttributes["class"] }
>();

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props;

	return delegated;
});

const forwardedProps = useForwardProps(delegatedProps);
</script>

<template>
  <CalendarCell
    :class="cn('relative p-0 text-center text-sm focus-within:relative focus-within:z-20 [&:has([data-selected])]:rounded-md [&:has([data-selected])]:bg-accent [&:has([data-selected][data-outside-view])]:bg-accent/50', props.class)"
    v-bind="forwardedProps"
  >
    <slot />
  </CalendarCell>
</template>
