// examples/svelte-kit-example/src/lib/components/ui/calendar/calendar-header.svelte
<script lang="ts">
import { Calendar as CalendarPrimitive } from "bits-ui";
import { cn } from "$lib/utils.js";

type $$Props = CalendarPrimitive.HeaderProps;

let className: $$Props["class"] = undefined;
export { className as class };
</script>

<CalendarPrimitive.Header
	class={cn("relative flex w-full items-center justify-between pt-1", className)}
	{...$$restProps}
>
	<slot />
</CalendarPrimitive.Header>

// examples/nuxt-example/components/ui/calendar/CalendarHeader.vue
<script lang="ts" setup>
import { type HTMLAttributes, computed } from "vue";
import {
	CalendarHeader,
	type CalendarHeaderProps,
	useForwardProps,
} from "radix-vue";
import { cn } from "@/lib/utils";

const props = defineProps<
	CalendarHeaderProps & { class?: HTMLAttributes["class"] }
>();

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props;

	return delegated;
});

const forwardedProps = useForwardProps(delegatedProps);
</script>

<template>
  <CalendarHeader :class="cn('relative flex w-full items-center justify-between pt-1', props.class)" v-bind="forwardedProps">
    <slot />
  </CalendarHeader>
</template>
