// examples/nuxt-example/components/ui/alert/Alert.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { type AlertVariants, alertVariants } from ".";
import { cn } from "@/lib/utils";

const props = defineProps<{
	class?: HTMLAttributes["class"];
	variant?: AlertVariants["variant"];
}>();
</script>

<template>
  <div :class="cn(alertVariants({ variant }), props.class)" role="alert">
    <slot />
  </div>
</template>

// examples/svelte-kit-example/src/lib/components/ui/alert/alert.svelte
<script lang="ts">
import type { HTMLAttributes } from "svelte/elements";
import { alertVariants, type Variant } from ".";
import { cn } from "$lib/utils";

type $$Props = HTMLAttributes<HTMLDivElement> & {
	variant?: Variant;
};

let className: $$Props["class"] = undefined;
export let variant: $$Props["variant"] = "default";
export { className as class };
</script>

<div class={cn(alertVariants({ variant }), className)} {...$$restProps} role="alert">
	<slot />
</div>
