// examples/svelte-kit-example/src/lib/components/ui/drawer/drawer-overlay.svelte
<script lang="ts">
import { Drawer as DrawerPrimitive } from "vaul-svelte";
import { cn } from "$lib/utils.js";

type $$Props = DrawerPrimitive.OverlayProps;

export let el: $$Props["el"] = undefined;
let className: $$Props["class"] = undefined;
export { className as class };
</script>

<DrawerPrimitive.Overlay
	bind:el
	class={cn("fixed inset-0 z-50 bg-black/80", className)}
	{...$$restProps}
>
	<slot />
</DrawerPrimitive.Overlay>

// examples/nuxt-example/components/ui/drawer/DrawerOverlay.vue
<script lang="ts" setup>
import { DrawerOverlay } from "vaul-vue";
import type { DialogOverlayProps } from "radix-vue";
import { type HtmlHTMLAttributes, computed } from "vue";
import { cn } from "@/lib/utils";

const props = defineProps<
	DialogOverlayProps & { class?: HtmlHTMLAttributes["class"] }
>();

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props;

	return delegated;
});
</script>

<template>
  <DrawerOverlay v-bind="delegatedProps" :class="cn('fixed inset-0 z-50 bg-black/80', props.class)" />
</template>
