// examples/svelte-kit-example/src/lib/components/ui/alert-dialog/alert-dialog-description.svelte
<script lang="ts">
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { cn } from "$lib/utils.js";

type $$Props = AlertDialogPrimitive.DescriptionProps;

let className: $$Props["class"] = undefined;
export { className as class };
</script>

<AlertDialogPrimitive.Description
	class={cn("text-muted-foreground text-sm", className)}
	{...$$restProps}
>
	<slot />
</AlertDialogPrimitive.Description>

// examples/nuxt-example/components/ui/alert-dialog/AlertDialogDescription.vue
<script setup lang="ts">
import { type HTMLAttributes, computed } from "vue";
import {
	AlertDialogDescription,
	type AlertDialogDescriptionProps,
} from "radix-vue";
import { cn } from "@/lib/utils";

const props = defineProps<
	AlertDialogDescriptionProps & { class?: HTMLAttributes["class"] }
>();

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props;

	return delegated;
});
</script>

<template>
  <AlertDialogDescription
    v-bind="delegatedProps"
    :class="cn('text-sm text-muted-foreground', props.class)"
  >
    <slot />
  </AlertDialogDescription>
</template>
