// examples/svelte-kit-example/src/lib/components/ui/toggle/toggle.svelte
<script lang="ts">
import { Toggle as TogglePrimitive } from "bits-ui";
import { toggleVariants, type Size, type Variant } from "./index.js";
import { cn } from "$lib/utils";

type $$Props = TogglePrimitive.Props & {
	variant?: Variant;
	size?: Size;
};
type $$Events = TogglePrimitive.Events;

let className: any = undefined;
export let variant: $$Props["variant"] = "default";
export let size: $$Props["size"] = "default";
export let pressed: $$Props["pressed"] = undefined;
export { className as class };
</script>

<TogglePrimitive.Root
	bind:pressed
	class={cn(toggleVariants({ variant, size, className }))}
	{...$$restProps}
	on:click
	on:keydown
>
	<slot />
</TogglePrimitive.Root>

// examples/nuxt-example/components/ui/toggle/Toggle.vue
<script setup lang="ts">
import { type HTMLAttributes, computed } from "vue";
import {
	Toggle,
	type ToggleEmits,
	type ToggleProps,
	useForwardPropsEmits,
} from "radix-vue";
import { type ToggleVariants, toggleVariants } from ".";
import { cn } from "@/lib/utils";

const props = withDefaults(
	defineProps<
		ToggleProps & {
			class?: HTMLAttributes["class"];
			variant?: ToggleVariants["variant"];
			size?: ToggleVariants["size"];
		}
	>(),
	{
		variant: "default",
		size: "default",
		disabled: false,
	},
);

const emits = defineEmits<ToggleEmits>();

const delegatedProps = computed(() => {
	const { class: _, size, variant, ...delegated } = props;

	return delegated;
});

const forwarded = useForwardPropsEmits(delegatedProps, emits);
</script>

<template>
  <Toggle
    v-bind="forwarded"
    :class="cn(toggleVariants({ variant, size }), props.class)"
  >
    <slot />
  </Toggle>
</template>
