// examples/nuxt-example/components/ui/range-calendar/RangeCalendarHeader.vue
<script lang="ts" setup>
import { type HTMLAttributes, computed } from "vue";
import {
	RangeCalendarHeader,
	type RangeCalendarHeaderProps,
	useForwardProps,
} from "radix-vue";
import { cn } from "@/lib/utils";

const props = defineProps<
	RangeCalendarHeaderProps & { class?: HTMLAttributes["class"] }
>();

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props;

	return delegated;
});

const forwardedProps = useForwardProps(delegatedProps);
</script>

<template>
  <RangeCalendarHeader :class="cn('relative flex w-full items-center justify-between pt-1', props.class)" v-bind="forwardedProps">
    <slot />
  </RangeCalendarHeader>
</template>

// examples/svelte-kit-example/src/lib/components/ui/range-calendar/range-calendar-header.svelte
<script lang="ts">
import { RangeCalendar as RangeCalendarPrimitive } from "bits-ui";
import { cn } from "$lib/utils.js";

type $$Props = RangeCalendarPrimitive.HeaderProps;

let className: $$Props["class"] = undefined;
export { className as class };
</script>

<RangeCalendarPrimitive.Header
	class={cn("relative flex w-full items-center justify-between pt-1", className)}
	{...$$restProps}
>
	<slot />
</RangeCalendarPrimitive.Header>
