// dev/solidjs/src/routes/index.tsx
import { Show } from "solid-js";
import { effect } from "solid-js/web";
import { client } from "~/lib/client";

export default function Home() {
	const session = client.useSession();
	// effect(() => {
	// 	console.log(session().data?.session)
	// })

	return (
		<main class="text-center mx-auto text-gray-700 p-4 min-h-screen flex flex-col items-center justify-center">
			<Show
				fallback={<button
					class="bg-sky-600 text-white px-4 py-2 rounded-md"
					onclick={async () => {
						await client.signIn.social({
							provider: "github",
						});
					}}
				>
					Continue with github
				</button>}
				when={!!session().data?.session}
			>
				<div class="flex flex-col gap-2 border border-blue-400/10 px-6 py-5">
					<p class="text-2xl text-white">{session()?.data?.user.name}</p>
					<p>{session().data?.user.email}</p>
					<button
						class="bg-sky-600 text-white px-4 py-2 rounded-md"
						onclick={async () => {
							await client.signOut();
						}}
					>
						Signout
					</button>
				</div>
			</Show>
		</main>
	);
}

// dev/svelte/src/routes/+page.svelte
<script lang="ts">
  import { client } from "$lib/client";

  const session = client.$session;
</script>

<div
  style="display: flex; min-height: 100vh; align-items: center; justify-content: center;"
>
  <div
    style="display: flex; flex-direction: column; gap: 10px; border-radius: 10px; border: 1px solid #4B453F; padding: 20px; margin-top: 10px;"
  >
    <div>
      {#if $session}
        <div>
          <p>
            {$session?.user.name}
          </p>
          <p>
            {$session?.user.email}
          </p>
          <button
            on:click={async () => {
              await client.signOut();
            }}
          >
            Signout
          </button>
        </div>
      {:else}
        <button
          on:click={async () => {
            await client.signIn.social({
              provider: "github",
            });
          }}
        >
          Continue with github
        </button>
      {/if}
    </div>
  </div>
</div>

<style>
  :root {
    font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
    line-height: 1.5;
    font-weight: 400;

    color-scheme: light dark;
    color: rgba(255, 255, 255, 0.87);
    background-color: #242424;

    font-synthesis: none;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  button {
    border-radius: 8px;
    border: 1px solid transparent;
    padding: 0.6em 1.2em;
    font-size: 1em;
    font-weight: 500;
    font-family: inherit;
    background-color: #1a1a1a;
    cursor: pointer;
    transition: border-color 0.25s;
  }
  button:hover {
    border-color: #646cff;
  }
  button:focus,
  button:focus-visible {
    outline: 4px auto -webkit-focus-ring-color;
  }
</style>
