// examples/tanstack-example/app/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'
import { signIn, signOut, useSession } from '~/lib/client/auth';

export const Route = createFileRoute('/')({
  component: Home,
})

function Home() {
  const { data } = useSession();

  return (
    <div>
      {data?.user && (
        <div>
          <p>Name: {data.user.name}</p>
          <p>Email: {data.user.email}</p>
          <p>Session ID: {data.session.id}</p>
          <button type="button" onClick={() => signOut()}>
            Sign Out
          </button>
        </div>
      )}
    </div>
  )
}

// examples/svelte/src/routes/+page.svelte
<script lang="ts">
	import { client, session } from '$lib/auth/client';
</script>

<div>
	{#if $session}
		<h1>Welcome {$session.firstName} {$session.lastName}</h1>
		<p>{$session.email}</p>
		<button
			on:click={async () => {
				await client.signOut();
				session.set(null);
			}}>Sign Out</button
		>
	{:else}
		<h1>Sign In</h1>
	{/if}
</div>

<button
	on:click={async () => {
		await client.signInOrSignUp({
			provider: 'github',
			signUp: {
				firstName: {
					from: 'first_name'
				},
				lastName: {
					from: 'last_name'
				}
			}
		});
	}}
>
	Continue with Github
</button>
