// examples/nuxt-example/components/ui/calendar/CalendarHeading.vue
<script lang="ts" setup>
import { type HTMLAttributes, computed } from "vue";
import {
	CalendarHeading,
	type CalendarHeadingProps,
	useForwardProps,
} from "radix-vue";
import { cn } from "@/lib/utils";

const props = defineProps<
	CalendarHeadingProps & { class?: HTMLAttributes["class"] }
>();

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props;

	return delegated;
});

const forwardedProps = useForwardProps(delegatedProps);
</script>

<template>
  <CalendarHeading
    v-slot="{ headingValue }"
    :class="cn('text-sm font-medium', props.class)"
    v-bind="forwardedProps"
  >
    <slot :heading-value>
      {{ headingValue }}
    </slot>
  </CalendarHeading>
</template>

// examples/svelte-kit-example/src/lib/components/ui/calendar/calendar-heading.svelte
<script lang="ts">
import { Calendar as CalendarPrimitive } from "bits-ui";
import { cn } from "$lib/utils.js";

type $$Props = CalendarPrimitive.HeadingProps;

let className: string | undefined | null = undefined;
export { className as class };
</script>

<CalendarPrimitive.Heading
	let:headingValue
	class={cn("text-sm font-medium", className)}
	{...$$restProps}
>
	<slot {headingValue}>
		{headingValue}
	</slot>
</CalendarPrimitive.Heading>
