// examples/astro-example/src/components/ui/table.tsx
import { cn } from "@/libs/cn";
import { type ComponentProps, splitProps } from "solid-js";

export const Table = (props: ComponentProps<"table">) => {
	const [local, rest] = splitProps(props, ["class"]);

	return (
		<div class="w-full overflow-auto">
			<table
				class={cn("w-full caption-bottom text-sm", local.class)}
				{...rest}
			/>
		</div>
	);
};

export const TableHeader = (props: ComponentProps<"thead">) => {
	const [local, rest] = splitProps(props, ["class"]);

	return <thead class={cn("[&_tr]:border-b", local.class)} {...rest} />;
};

export const TableBody = (props: ComponentProps<"tbody">) => {
	const [local, rest] = splitProps(props, ["class"]);

	return (
		<tbody class={cn("[&_tr:last-child]:border-0", local.class)} {...rest} />
	);
};

export const TableFooter = (props: ComponentProps<"tfoot">) => {
	const [local, rest] = splitProps(props, ["class"]);

	return (
		<tbody
			class={cn("bg-primary font-medium text-primary-foreground", local.class)}
			{...rest}
		/>
	);
};

export const TableRow = (props: ComponentProps<"tr">) => {
	const [local, rest] = splitProps(props, ["class"]);

	return (
		<tr
			class={cn(
				"border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted",
				local.class,
			)}
			{...rest}
		/>
	);
};

export const TableHead = (props: ComponentProps<"th">) => {
	const [local, rest] = splitProps(props, ["class"]);

	return (
		<th
			class={cn(
				"h-10 px-2 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
				local.class,
			)}
			{...rest}
		/>
	);
};

export const TableCell = (props: ComponentProps<"td">) => {
	const [local, rest] = splitProps(props, ["class"]);

	return (
		<td
			class={cn(
				"p-2 align-middle [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
				local.class,
			)}
			{...rest}
		/>
	);
};

export const TableCaption = (props: ComponentProps<"caption">) => {
	const [local, rest] = splitProps(props, ["class"]);

	return (
		<caption
			class={cn("mt-4 text-sm text-muted-foreground", local.class)}
			{...rest}
		/>
	);
};

// docs/components/ui/table.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

const Table = (
    {
        ref,
        className,
        ...props
    }: React.HTMLAttributes<HTMLTableElement> & {
        ref: React.RefObject<HTMLTableElement>;
    }
) => (<div className="relative w-full overflow-auto">
    <table
        ref={ref}
        className={cn("w-full caption-bottom text-sm", className)}
        {...props}
    />
</div>);
Table.displayName = "Table";

const TableHeader = (
    {
        ref,
        className,
        ...props
    }: React.HTMLAttributes<HTMLTableSectionElement> & {
        ref: React.RefObject<HTMLTableSectionElement>;
    }
) => (<thead ref={ref} className={cn("[&_tr]:border-b", className)} {...props} />);
TableHeader.displayName = "TableHeader";

const TableBody = (
    {
        ref,
        className,
        ...props
    }: React.HTMLAttributes<HTMLTableSectionElement> & {
        ref: React.RefObject<HTMLTableSectionElement>;
    }
) => (<tbody
    ref={ref}
    className={cn("[&_tr:last-child]:border-0", className)}
    {...props}
/>);
TableBody.displayName = "TableBody";

const TableFooter = (
    {
        ref,
        className,
        ...props
    }: React.HTMLAttributes<HTMLTableSectionElement> & {
        ref: React.RefObject<HTMLTableSectionElement>;
    }
) => (<tfoot
    ref={ref}
    className={cn(
        "border-t bg-muted/50 font-medium [&>tr]:last:border-b-0",
        className,
    )}
    {...props}
/>);
TableFooter.displayName = "TableFooter";

const TableRow = (
    {
        ref,
        className,
        ...props
    }: React.HTMLAttributes<HTMLTableRowElement> & {
        ref: React.RefObject<HTMLTableRowElement>;
    }
) => (<tr
    ref={ref}
    className={cn(
        "border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted",
        className,
    )}
    {...props}
/>);
TableRow.displayName = "TableRow";

const TableHead = (
    {
        ref,
        className,
        ...props
    }: React.ThHTMLAttributes<HTMLTableCellElement> & {
        ref: React.RefObject<HTMLTableCellElement>;
    }
) => (<th
    ref={ref}
    className={cn(
        "h-10 px-2 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
        className,
    )}
    {...props}
/>);
TableHead.displayName = "TableHead";

const TableCell = (
    {
        ref,
        className,
        ...props
    }: React.TdHTMLAttributes<HTMLTableCellElement> & {
        ref: React.RefObject<HTMLTableCellElement>;
    }
) => (<td
    ref={ref}
    className={cn(
        "p-2 align-middle [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
        className,
    )}
    {...props}
/>);
TableCell.displayName = "TableCell";

const TableCaption = (
    {
        ref,
        className,
        ...props
    }: React.HTMLAttributes<HTMLTableCaptionElement> & {
        ref: React.RefObject<HTMLTableCaptionElement>;
    }
) => (<caption
    ref={ref}
    className={cn("mt-4 text-sm text-muted-foreground", className)}
    {...props}
/>);
TableCaption.displayName = "TableCaption";

export {
	Table,
	TableHeader,
	TableBody,
	TableFooter,
	TableHead,
	TableRow,
	TableCell,
	TableCaption,
};
