// examples/nuxt-example/components/ui/breadcrumb/BreadcrumbSeparator.vue
<script lang="ts" setup>
import type { HTMLAttributes } from "vue";
import { ChevronRightIcon } from "@radix-icons/vue";
import { cn } from "@/lib/utils";

const props = defineProps<{
	class?: HTMLAttributes["class"];
}>();
</script>

<template>
  <li
    role="presentation"
    aria-hidden="true"
    :class="cn('[&>svg]:size-3.5', props.class)"
  >
    <slot>
      <ChevronRightIcon />
    </slot>
  </li>
</template>

// examples/svelte-kit-example/src/lib/components/ui/breadcrumb/breadcrumb-separator.svelte
<script lang="ts">
import { cn } from "$lib/utils";
import ChevronRight from "svelte-radix/ChevronRight.svelte";
import type { HTMLLiAttributes } from "svelte/elements";

type $$Props = HTMLLiAttributes & {
	el?: HTMLLIElement;
};

export let el: $$Props["el"] = undefined;
let className: $$Props["class"] = undefined;
export { className as class };
</script>

<li
	role="presentation"
	aria-hidden="true"
	class={cn("[&>svg]:size-3.5", className)}
	bind:this={el}
	{...$$restProps}
>
	<slot>
		<ChevronRight />
	</slot>
</li>
