// examples/nuxt-example/components/ui/breadcrumb/BreadcrumbLink.vue
<script lang="ts" setup>
import type { HTMLAttributes } from "vue";
import { Primitive, type PrimitiveProps } from "radix-vue";
import { cn } from "@/lib/utils";

const props = withDefaults(
	defineProps<PrimitiveProps & { class?: HTMLAttributes["class"] }>(),
	{
		as: "a",
	},
);
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="cn('transition-colors hover:text-foreground', props.class)"
  >
    <slot />
  </Primitive>
</template>

// examples/svelte-kit-example/src/lib/components/ui/breadcrumb/breadcrumb-link.svelte
<script lang="ts">
import type { HTMLAnchorAttributes } from "svelte/elements";
import { cn } from "$lib/utils.js";

type $$Props = HTMLAnchorAttributes & {
	el?: HTMLAnchorElement;
	asChild?: boolean;
};

export let href: $$Props["href"] = undefined;
export let el: $$Props["el"] = undefined;
export let asChild: $$Props["asChild"] = false;
let className: $$Props["class"] = undefined;
export { className as class };

let attrs: Record<string, unknown>;

$: attrs = {
	class: cn("hover:text-foreground transition-colors", className),
	href,
	...$$restProps,
};
</script>

{#if asChild}
	<slot {attrs} />
{:else}
	<a bind:this={el} {...attrs} {href}>
		<slot {attrs} />
	</a>
{/if}
