// examples/nuxt-example/components/ui/table/TableHead.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { cn } from "@/lib/utils";

const props = defineProps<{
	class?: HTMLAttributes["class"];
}>();
</script>

<template>
  <th :class="cn('h-10 px-2 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-0.5', props.class)">
    <slot />
  </th>
</template>

// examples/svelte-kit-example/src/lib/components/ui/table/table-head.svelte
<script lang="ts">
import { cn } from "$lib/utils";
import type { HTMLThAttributes } from "svelte/elements";

type $$Props = HTMLThAttributes;

let className: $$Props["class"] = undefined;
export { className as class };
</script>

<th
	class={cn(
		"text-muted-foreground h-10 px-2 text-left align-middle font-medium [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
		className
	)}
	{...$$restProps}
>
	<slot />
</th>
